### ISSUE TITLE
Exception when fetching crop of annotations composed of many points

### ISSUE THREAD

**Issue by elodieburtin** [cytomine/Cytomine-core-legacy#1164]
When fetching the crop of an annotation with `GET /api/userannotation/{id}/crop.png?draw=true`, for some annotations, a runtime exception is raised (Exception Message: Content has been consumed). The problem seems to occur when fetching crops of annotations composed of a lot of points. Moreover, it only occurs when the `draw` parameter is set to true.

Example: https://demo.cytomine.coop/api/userannotation/2307130/crop.png?draw=true

**Comment by geektortoise** [comment]
Hello, 

When draw parameter was set to true, the url was really long (need to write the coordinates of the points) so the GET was converted to POST and we had an exception "Content (of the stream) already consumed".
The error was not present in development environnement.

Fixed by 9630ffd0cfa2e083a321ece28928050fbb098547

Example : https://demo.cytomine.coop/api/userannotation/2307130/crop.png?draw=true&maxSize=256
