### ISSUE TITLE
Enable 3rd party API access?

### ISSUE THREAD

**Issue by AustinGil** [cytomine/Cytomine-core-legacy#1184]
My company is testing out Cytomine, and it looks really great. I've been asked to build a custom UI that integrates with the Cytomine API, but I just keep getting CORS issues any time I try to make a fetch request to the API.

The request looks like:
```js
fetch(`${HOST}/api/ontology.json`, {
  credentials: "include",
  headers: {
    "proxy-authorization":
      "Basic [some code]",
    "proxy-connection": "keep-alive",
  },
  mode: "cors",
})
```

But I keep getting the error:
```
Access to fetch at '[MY HOST]/api/ontology.json' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

Is there any way to open up access to the API for 3rd party requests?

**Comment by geektortoise** [comment]
Hello, 

With the current Cytomine-bootstrap, we don't have this problem because it is the same URL for the front-end and the back-end
https://github.com/cytomine/Cytomine-bootstrap/blob/master/configs/nginx/nginx.conf.sample#L46

Usually, if you want a website to communicate with an API with a different URL, you need to allow CORS requests not only in your front side but also in the proxy of the API server. It is not a Cytomine configuration.

In your case, you allowed a CORS request to be sent, you also need to allow CORS requests to be received by the proxy (nginx) of Cytomine.
You need to adapt the nginx configuration file to allow CORS requests coming from your authorized URLs and it should be ok.

**Comment by geektortoise** [comment]
As it is not a bug in the core, I close this ticket.

**Comment by AustinGil** [comment]
@geektortoise Thanks for the reply. I was hoping there might be some configuration we could set to allow access from different domains, but I figured I should check the NGINX config as well. 

I was able to find the NGINX conf file, but still not sure how to allow for other domain access. If you have an example, that would be very helpful.

**Comment by geektortoise** [comment]
I've never had this need before so I don't have example.

Did you check https://enable-cors.org/server_nginx.html ?
The 
        add_header 'Access-Control-Allow-Origin' '*';
means you allow all sources. In your case, it will be only the trusted one but as nginx is sometimes tricky to configure, test firstly with default parameter. 

Have a nice day

**Comment by AustinGil** [comment]
Thanks @geektortoise. I've been trying to fiddle with the NGINX conf for a couple days now with no luck. Do you know where that line would go? 

Maybe inside the `server {` block, or inside the `location /api {` block?

Do you think I need to add something like
```
if ($request_method = 'OPTIONS') {
        # Tell client that this pre-flight info is valid for 20 days
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
}
```
(from https://gist.github.com/Stanback/7145487)
