### ISSUE TITLE
[CYTO-757] Sonar Review #1 - Grails Public Controller Method

### ISSUE THREAD

**Issue by stevben** [cytomine/Cytomine-core-legacy#363]
<b><i>[reporter="stevben", created="lun., 14 janv. 2013 16:30:13 +0100"]</i></b>

<p>Violation detail:</p>

<blockquote>
<p>Violation in class RestController. The Grails controller has a public method add. This should be a closure property or moved</p></blockquote>

<p>Message from reviewer:</p>

<blockquote>
<p>Sonar a-t-il raison sur ce point ? Il y a eu pas mal de changements dans Grails.</p>

<p>(je teste la création de demandes jira depuis sonar en même temps)</p></blockquote>

<p>Check it on Sonar: <a href="http://sonar.cytomine.be/project_reviews/view/1" class="external-link">http://sonar.cytomine.be/project_reviews/view/1</a></p>

**Comment by loic911** [comment]
http://grails.org/doc/latest/guide/theWebLayer.html#controllers

"In earlier versions of Grails actions were implemented with Closures. This is still supported, but the preferred approach is to use methods.

Leveraging methods instead of Closure properties has some advantages:
-Memory efficient
-Allow use of stateless controllers (singleton scope)
-You can override actions from subclasses and call the overridden superclass method with super.actionName()
-Methods can be intercepted with standard proxying mechanisms, something that is complicated to do with Closures since they're fields.

=> FALSE POSTIVE

http://codenarc.sourceforge.net/codenarc-rules-grails.html
"
NOTE: This rule has been disabled by default (i.e., by setting its enabled property to
false). Given that Grails 2.x allows and encourages controller actions to be defined as methods
instead of closures, this rule makes no sense for Grails 2.x projects."
